FROM python:3.10

ENV APP_DIR /fedrit

WORKDIR $APP_DIR

COPY requirements.txt $APP_DIR
RUN pip install -r requirements.txt

COPY . $APP_DIR

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "fedrit.wsgi:application"]