# Generated by Django 4.1.5 on 2023-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='google_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
