# Generated by Django 4.1.5 on 2023-02-11 00:19

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_type',
            field=models.CharField(choices=[('SUB', 'Subreddit'), ('IMGBOARD', 'ImageBoard'), ('FORUM', 'Forum')], default='SUB', max_length=20),
        ),
        migrations.AlterField(
            model_name='community',
            name='platform',
            field=models.ForeignKey(default=api.models.host_platform, on_delete=django.db.models.deletion.CASCADE, to='api.platform'),
        ),
        migrations.AlterField(
            model_name='Post',
            name='platform',
            field=models.ForeignKey(default=api.models.host_platform, on_delete=django.db.models.deletion.DO_NOTHING, to='api.platform'),
        ),
    ]
