# Generated by Django 4.1.5 on 2023-01-31 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='pgpkey',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='pgpkey',
        ),
    ]
