# Generated by Django 4.1.5 on 2023-05-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_id_platform_uuid_platform_unique_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='uuid',
            new_name='id',
        ),
    ]
