# Generated by Django 4.1.5 on 2023-03-24 16:27

import api.models
import api.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=api.utils.gen_token_str, max_length=47)),
                ('platform', models.OneToOneField(default=api.models.host_platform, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.platform')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usertoken', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
