# Generated by Django 4.1.5 on 2023-03-24 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0006_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='host',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.platformuser'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='domain',
            field=models.CharField(default='fedrit.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(default=('fedrit',), max_length=30),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='platform_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='platform_user_set', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.platformuser'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usertoken', to='api.platformuser'),
        ),
    ]
