# Generated by Django 4.1.1 on 2022-09-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedrit_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.TextField(default='RSA')),
                ('key_length', models.IntegerField(default=4096)),
                ('name_real', models.TextField()),
                ('name_comment', models.TextField()),
                ('name_email', models.TextField()),
            ],
        ),
    ]
