# Generated by Django 4.1.1 on 2022-09-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedrit_app', '0003_post_created_sub_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sub',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
