# Generated by Django 4.1.1 on 2022-09-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedrit_app', '0004_alter_pgp_id_alter_post_id_alter_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgp',
            name='fingerprint',
            field=models.TextField(null=True),
        ),
    ]
