# Generated by Django 4.1.1 on 2022-09-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedrit_app', '0005_pgp_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgp',
            name='fingerprint',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pgp',
            name='name_comment',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='pgp',
            name='name_email',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pgp',
            name='name_real',
            field=models.TextField(max_length=50),
        ),
    ]
